[workspace]
members = ["crates/parser", "crates/solver"]
resolver = "2"


[workspace.lints.clippy]
must_use_candidate = "allow"
float_cmp = "allow"
pedantic = { level = "warn", priority = -1 }


[workspace.dependencies]
thiserror = "2"
parser = { path = "crates/parser" }
solver = { path = "crates/solver" }
