[workspace]
members = ["crates/matrix", "crates/parser", "crates/result", "crates/solver"]
resolver = "2"


[workspace.lints.clippy]
must_use_candidate = "allow"
float_cmp = "allow"
# pedantic = { level = "warn", priority = -1 }
# nursery = { level = "warn", priority = -1 }

[workspace.dependencies]
thiserror = "2"
faer = "0.21.7"
parser = { path = "crates/parser" }
solver = { path = "crates/solver" }
matrix = { path = "crates/matrix" }
