[workspace]
members = ["crates/parser"]
resolver = "2"


[workspace.lints.clippy]
must_use_candidate = "allow"
pedantic = { level = "warn", priority = -1 }


[workspace.dependencies]
thiserror = "2"
parser = { path = "crates/parser" }
